export const cronogramaDatav0 = [
  {
    day: "Lunes",
    date: new Date("11/13/2023"),
    early: [
      {
        start: "09:00am",
        end: "13:00hrs",
        type: "rest",
        name: `Inscripciones`,
        speaker: "Anfitrión",
        country: "Perú",
      },
      {
        start: "13:00hrs",
        end: "14:00hrs",
        type: "lunch",
        name: "Descanso",
        speaker: null,
        country: null,
      },
    ],
    late: [
      {
        start: "15:00hrs",
        end: "16:00hrs",
        type: "rest",
        name: `Inscripciones`,
        speaker: "Anfitrión",
        country: "Perú",
      },
      {
        id: 9,
        start: "16:00hrs",
        end: "17:00hrs",
        type: "Ponencia",
        name: `Más allá de la Visión Humana: Técnicas para estudiar Fenómenos Biológicos basados en IA`,
        speaker: "Ph.D. Daniel Ochoa (ESPOL)",
        idSpeaker: 23,
        country: "Ecuador",
      },
      {
        id: 10,
        start: "17:00hrs",
        end: "18:30hrs",
        type: "Ponencia",
        name: `Mejorando la Realidad de Brasil con Inteligencia Artificial`,
        speaker: "Ph.D. Arlindo Galvão (CEIA)",
        idSpeaker: 17,
        country: "Brasil",
      },
      {
        start: "18:30hrs",
        end: "20:00hrs",
        type: "rest",
        name: `Inauguración: El comienzo de una semana maravillosa`,
        speaker: "Anfitrión",
        country: "Perú",
      },
    ],
  },
  {
    day: "Martes",
    date: new Date("11/14/2023"),
    early: [
      {
        id: 11,
        start: "09:00am",
        end: "10:00am",
        type: "Ponencia",
        name: "Detección de Neoantígenos mediante Transformadores y Aprendizaje por Transferencia",
        speaker: "MSc. Vicente Machaca (USALLE)",
        idSpeaker: 33,
        country: "Perú",
      },
      {
        id: 12,
        start: "10:00am",
        end: "11:00am",
        type: "Ponencia",
        name: "Grounded Theory como Complemento para Obtener y Validar Requerimientos de Software",
        speaker: "Dr. Ítalo Donoso (UCN)",
        idSpeaker: 26,
        country: "Chile",
      },
      {
        id: 13,
        start: "11:30am",
        end: "13:00hrs",
        type: "Taller",
        name: "Inteligencia Artificial aplicada a la Música",
        speaker: "Ph.D. Arlindo Galvão (CEIA)",
        idSpeaker: 17,
        country: "Brasil",
      },
      {
        start: "13:00hrs",
        end: "14:00hrs",
        type: "lunch",
        name: "Descanso",
        speaker: null,
        country: null,
      },
    ],
    late: [
      {
        start: "14:00hrs",
        end: "16:00hrs",
        type: "contest",
        name: "Concurso de robótica",
        speaker: null,
        country: null,
      },
      {
        id: 14,
        start: "16:00hrs",
        end: "17:00hrs",
        type: "Ponencia",
        name: "Fake news en las Redes Sociales: Análisis de su Relación con las Emociones y las Intenciones",
        speaker: "Ph.D. Claudio Meneses (UCN)",
        idSpeaker: 24,
        country: "Chile",
      },
      {
        id: 15,
        start: "17:00hrs",
        end: "18:00hrs",
        type: "Ponencia",
        name: "Experiencias y Herramientas de DevOps",
        speaker: "MSc. Diego Urrutia (UCN)",
        idSpeaker: 25,
        country: "Chile",
      },
    ],
  },
  {
    day: "Miércoles",
    date: new Date("11/15/2023"),
    early: [
      {
        id: 16,
        start: "09:00am",
        end: "10:00am",
        type: "Ponencia",
        name: "Más allá de la Caja Negra: Inteligencia Artificial Responsable y Explicabilidad",
        speaker: "MSc. Rosa Paccotacya (UNICAMP)",
        idSpeaker: 32,
        country: "Perú",
      },
      {
        id: 17,
        start: "10:00am",
        end: "11:00am",
        type: "Ponencia",
        name: "¿Cómo Investigar en Ciencia de la Computación?",
        speaker: "Ph.D. Yvan Tupac (UCSP)",
        idSpeaker: 18,
        country: "Perú",
      },
      {
        start: "11:30am",
        end: "13:00hrs",
        type: "Taller",
        name: "Revisiones Sistemáticas en Ciencia de la Computación",
        speaker: "Ph.D. Yvan Tupac (UCSP)",
        idSpeaker: 18,
        country: "Perú",
      },
      {
        start: "13:00hrs",
        end: "14:00hrs",
        type: "lunch",
        name: "Descanso",
        speaker: null,
        country: null,
      },
    ],
    late: [
      {
        id: 19,
        start: "16:00hrs",
        end: "17:30hrs",
        type: "Ponencia",
        name: "ITS & Smart City of  Necessity",
        speaker: "Ph.D. Yeon Soo Kim",
        idSpeaker: 22,
        country: "Corea del sur",
      },
      {
        id: 20,
        start: "17:30hrs",
        end: "19:00hrs",
        type: "Ponencia",
        name: "Aprendizaje Profundo en Visión Computacional en Dispositivos con Recursos Computacionales Limitados",
        speaker: "Ph.D. Arlindo Galvão (CEIA)",
        idSpeaker: 17,
        country: "Brasil",
      },
    ],
  },
  {
    day: "Jueves",
    date: new Date("11/16/2023"),
    early: [
      {
        id: 21,
        start: "09:00am",
        end: "10:00am",
        type: "Ponencia",
        name: "Desarrollo de Software Guiado por Dominio",
        speaker: "Dr. Edgar Sarmiento (UNSA)",
        idSpeaker: 19,
        country: "Perú",
      },
      {
        id: 22,
        start: "10:00am",
        end: "11:00am",
        type: "Ponencia",
        name: "Ajuste de Hiperparámetros en la Selección de un Modelo de Aprendizaje Automático",
        speaker: "Dr. Roberto Espinosa (UTA)",
        idSpeaker: 28,
        country: "Chile",
      },
      {
        start: "11:30am",
        end: "13:00hrs",
        type: "Taller",
        name: "Análisis Automático de Código Fuente",
        speaker: "Dr. Edgar Sarmiento (UNSA)",
        idSpeaker: 19,
        country: "Perú",
      },
      {
        start: "13:00hrs",
        end: "14:00hrs",
        type: "lunch",
        name: "Descanso",
        speaker: null,
        country: null,
      },
    ],
    late: [
      {
        start: "14:00hrs",
        end: "16:00hrs",
        type: "contest",
        name: "Concurso de Programación",
        speaker: null,
        country: null,
      },
      {
        id: 24,
        start: "16:00hrs",
        end: "17:00hrs",
        type: "Ponencia",
        name: "Identificación Automática de Defectos en Software",
        speaker: "Ph.D. Jesús Bellido (UTEC)",
        idSpeaker: 30,
        country: "Perú",
      },
      {
        id: 25,
        start: "17:00hrs",
        end: "18:00hrs",
        type: "Ponencia",
        name: "Inteligencia Artificial Generativa y Multimodalidad",
        speaker: "Dr. Cesar Beltrán (PUCP)",
        idSpeaker: 29,
        country: "Perú",
      },
    ],
  },
  {
    day: "Viernes",
    date: new Date("11/17/2023"),
    early: [
      {
        id: 26,
        start: "09:00am",
        end: "10:00am",
        type: "Ponencia",
        name: "Serverless Computing: Retos y Líneas de Investigación",
        speaker: "Dr. Alvaro Mamani (UNSA)",
        idSpeaker: 20,
        country: "Perú",
      },
      {
        id: 27,
        start: "10:00am",
        end: "11:00am",
        type: "Ponencia",
        name: "Inteligencia Artificial y Ciberseguridad",
        speaker: "Dr. Julio Santisteban (UCSP)",
        idSpeaker: 31,
        country: "Perú",
      },
      {
        start: "11:30am",
        end: "13:00hrs",
        type: "Taller",
        name: "AWS Academy Cloud Foundations",
        speaker: "Dr. Alvaro Mamani (UNSA)",
        idSpeaker: 20,
        country: "Perú",
      },
      {
        start: "13:00hrs",
        end: "14:00hrs",
        type: "lunch",
        name: "Descanso",
        speaker: null,
        country: null,
      },
    ],
    late: [
      {
        start: "14:00hrs",
        end: "16:00hrs",
        type: "contest",
        name: "Concurso de Conocimientos",
        speaker: null,
        country: null,
      },
      {
        id: 29,
        start: "16:00hrs",
        end: "17:00hrs",
        type: "Ponencia",
        name: "Programación de Restricciones",
        speaker: "Dr. Ricardo Valdivia (UTA)",
        idSpeaker: 27,
        country: "Chile",
      },
      {
        id: 30,
        start: "17:00hrs",
        end: "18:30hrs",
        type: "Ponencia",
        name: "Mejora de la Seguridad de las Imágenes en Color con Técnicas de Marca de Agua Robustas contra los Ataques de Ambigüedad",
        speaker: "Ph.D. Joshi Sandeep",
        idSpeaker: 21,
        country: "India",
      },
      {
        start: "18:30hrs",
        end: "20:00hrs",
        type: "rest",
        name: "Clausura: Una pausa hasta el próximo año",
        speaker: "Anfitrión",
        country: "Perú",
      },
    ],
  },
];
